dicksonNearfieldImplementation:=function(q,n);
	if not(IsPrimePower(q)) then print "q is not a prime power"; return 0; end if;
	p:=PrimeDivisors(n);
	if not(forall{x:x in p|(q-1) mod x eq 0}) then print "All prime divisors of n must divide q-1"; return 0; end if;
	if (q mod 4) eq 3 and (n mod 4) eq 0 then print "n cannot be a multiple of 4 if q = 3 (mod 4)"; return 0; end if;
	
	F:=GF(q);
	K:=ext<F|n>;
	c:=PrimitiveElement(K);
	
	/*In the nearfield construction the cosets of the multiplicative group generated by c^n  are represented by c^((q^i-1)/(q-1), but this representation is pretty inconvenient for computation; we'd much prefer to use the c^0 ... c^(n-1) representatives so we can just take logs and reduce modulo n. So, we're going to do the mapping up front.*/
		
	automorphismSequence:=[0:i in {0..n-1}];
	for i in {0..n-1} do
	  index:=((q^i-1) div (q-1)) mod n;
	  automorphismSequence[index+1]:=q^i; /* Magma indexes sequences 1-based */
	end for;
	
	/* Our points are ordered pairs of elements from K */
	points:={@<k1,k2>:k1,k2 in K@};
	
	/* mult is the product operation on the quasifield */
	mult:=function(a,b);
		if b eq 0 then return K!0;
		else return a^automorphismSequence[(Log(b) mod n)+1]*b;
		end if;
	end function;
	
	/* Standard affine coordinates for quasifield construction */
	lines:={{<x,mult(x,a)+b>:x in K}:a,b in K} join {{<c,y>:y in K}:c in K};
	pi:=FiniteAffinePlane<points|lines>;
	Pi,P,L:=ProjectiveEmbedding(pi);
	return Pi;
end function;
